name: Beta Release Creation

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update to Beta Version
        run: |
          sed -i '3s/.*/"message": "Study Tools voor Magister BETA"/' _locales/nl/messages.json
          sed -i '3s/.*/"message": "Study Tools for Magister BETA"/' _locales/en/messages.json

      - name: Upload Artifacts for Beta Release
        uses: actions/upload-artifact@v4
        with:
          name: Beta-Release-Files
          path: |
            _locales
            icons
            popup/dist
            src
            manifest.json
            updates.json
