name: Create Releases

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Compress Chromium Build
        run: |
          zip -r chromium.zip _locales icons popup/dist src manifest.json updates.json

      - name: Compress Firefox Build
        run: |
          mv manifest.json manifest-chromium.json
          mv manifest-firefox.json manifest.json
          zip -r firefox.zip _locales icons popup/dist src manifest.json updates.json
          mv manifest.json manifest-firefox.json
          mv manifest-chromium.json manifest.json

      - name: Upload Release Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Release-Files
          path: |
            chromium.zip
            firefox.zip
